theme: minima
title: Horton Hears a Who!
author: MJH
description: > # this means to ignore newlines until "baseurl:"
github blog site for testing.

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  horton-hears-a-who # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
